# Generated by Django 6.0.6 on 2026-06-15 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screener', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumeanalysis',
            name='recommended_role',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='resumeanalysis',
            name='semantic_score',
            field=models.FloatField(default=0),
        ),
    ]
